### ISSUE TITLE
Missed person's name in reminder

### ISSUE THREAD

**Issue by davidawright** [wballard/remi#14]
input:
"remind @davidwright to coordinate with Jim on Monday May 9 regarding schema changes"

Output:
"Got it. I'll remind @DavidWright to coordinate with on Monday at 12:00 PM EDT"

**Comment by wballard** [comment]
that's a cool one -- split in the middle. I updated LUIS with this, and added it to your todos

**Comment by ghost** [comment]
Hey!

I think you got your @davidawright wrong. You keep sending messages to @davidwright ;)
