### ISSUE TITLE
Change existing appt from 12PM to 9AM, Remi got day and time wrong

### ISSUE THREAD

**Issue by davidawright** [wballard/remi#15]
Had reminder set for next Monday (today is Wednesday) at 12PM.
My intention was to change the time but not the date, to Monday at 9AM.

Input:
change 12PM to 9AM
Output:
I'll change that to Today at 8:00 AM

**Comment by wballard** [comment]
try saying 
change that to 9am

**Comment by davidawright** [comment]
"Change that to 9am" - got the time right this time
then: "Change to 10am" - also got the time right this time
