### ISSUE TITLE
Remi doesn't know my time zone I guess?

### ISSUE THREAD

**Issue by drhayes** [wballard/remi#16]
> David Hayes·8:09 AM
> Remind me to check on Go errors at 9am today
> Remi·8:09 AM
> Got it. I'll remind @drhayes to check on go errors on Today at 4:00 AM CDT
> Reminder from @drhayes to check on go errors

Expected that to be 9:00 AM CDT.

**Comment by wballard** [comment]
mmm - date parsing....

all set

Remind @drhayes to check on Go errors at 9am today
@Remi·8:51 AM
Got it. I'll remind @drhayes to check on go errors on Today at 9:00 AM CDT
